Update menu

diff --git a/gerador/menu b/gerador/menu
--- a/gerador/menu
+++ b/gerador/menu
@@ -598,3 +598,303 @@ local Numb=1
 for arqs in $(ls ${SCPfrm}); do
 float_data "$arqs" "$Numb" && {
   script[$Numb]="$arqs"
+let Numb++
+  }
+done
+echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "ADMINISTAR MEDIENTE BOT DE TELEGAM  $ofc"
+script[$Numb]="ADMbot.sh"
+let Numb++
+echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "COMPARTIR ARCHIVO ONLINE            $ofc"
+script[$Numb]="apacheon.sh"
+echo -e "\033[1;93m-----------------------SEGURIDAD---------------------"
+#PROTECION
+let Numb++
+echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "FIREWALL BLOCK TORRENT              $ofc"
+script[$Numb]="blockBT.sh"
+let Numb++
+echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "FAIL2BAN PROTECION                  $ofc"
+script[$Numb]="fai2ban.sh"
+let Numb++
+echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "AUTENTIFICAR PROXY SQUID            $ofc"
+script[$Numb]="squidpass.sh"
+let Numb++
+echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "DESACTIVAR PASS ALFANUMERICO        $ofc"
+script[$Numb]="Unlock-Pass-VULTR.sh"
+echo -e "\033[1;93m--------------------AJUSTES INTERNOS-----------------"
+#AJUSTES INTERNOS
+let Numb++
+echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "TCP ACELERACION (BBR/PLUS)          $dev"
+script[$Numb]="tcp.sh"
+let Numb++
+#echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "AGREGAR DNS NETFLIX By @USA1_BOT    $ofc"
+#script[$Numb]="dns-netflix.sh"
+#let Numb++
+echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "ADMINISTRAR PUERTOS ACTIVOS         $ofc"
+script[$Numb]="ports.sh"
+let Numb++
+echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "Pass Root/Add root/Horario/etc..    $ofc"
+script[$Numb]="gestor.sh"
+#OPTIMIZADORES
+echo -e "\033[1;93m---------------------OPTIMIZADORES-------------------"
+let Numb++
+echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "Limpiar M. Ram/Librerias/etc..     $ofc"
+script[$Numb]="utils.sh"
+let Numb++
+echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "Limpiar Cache del Servidor         $ofc"
+script[$Numb]="optimizar.sh"
+let Numb++
+echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "DETALLES DE SISTEMA                $ofc"
+script[$Numb]="systeminf"
+#EXTRAS
+echo -e "\033[1;93m-------------------------EXTRAS----------------------"
+let Numb++
+echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "PAYLOAD FUERZA BRUTA               $ofc"
+script[$Numb]="paysnd.sh"
+let Numb++
+echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "SCANNER DE SUBDOMINIO              $ofc"
+script[$Numb]="ultrahost"
+let Numb++
+echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "PRUEBA DE VELOCIDAD                $ofc"
+script[$Numb]="speed.sh"
+let Numb++
+echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "PANEL WEB SSH (Ubuntu 14)          $dev2"
+script[$Numb]="panelweb.sh"
+let Numb++
+echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") " && msg -azu "VNC VIEWER                         $dev2"
+script[$Numb]="vnc"
+let Numb++
+echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") $(msg -ama "[!]") " && msg -verd "AGREGAR HERRAMIENTAS           $ofc"
+script[$Numb]="agregar"
+let Numb++
+echo -ne "$(msg -verd "[$Numb]") $(msg -verm2 ">") $(msg -ama "[!]") " && msg -verm2 "REMOVER HERRAMIENTAS           $ofc"
+script[$Numb]="remove"
+echo -ne "$(msg -verd "[0]") $(msg -verm2 ">") "&& msg -bra "\033[1;41mREGRESAR AL MENU"
+#echo -ne "$(msg -verd "[0]") $(msg -verm2 ">") " && msg -bra "$(fun_trans "  VOLVER")"
+script[0]="voltar"
+msg -bar2
+selection=$(selection_fun $Numb)
+[[ -e "${SCPfrm}/${script[$selection]}" ]] && {
+  ${SCPfrm}/${script[$selection]} 
+  } || {
+  case ${script[$selection]} in
+  "agregar")agregar_ferramenta;;
+  "remove")remove_ferramenta;;
+  "limpar")limpar_caches;;
+  "systeminf")systen_info;;
+  *)return 0;;
+  esac
+  }  
+}
+# Menu Instalaciones
+pid_inst () {
+[[ $1 = "" ]] && echo -e "\033[1;31m[OFF]" && return 0
+unset portas
+portas_var=$(lsof -V -i -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND")
+i=0
+while read port; do
+var1=$(echo $port | awk '{print $1}') && var2=$(echo $port | awk '{print $9}' | awk -F ":" '{print $2}')
+[[ "$(echo -e ${portas[@]}|grep "$var1 $var2")" ]] || {
+    portas[$i]="$var1 $var2\n"
+    let i++
+    }
+done <<< "$portas_var"
+[[ $(echo "${portas[@]}"|grep "$1") ]] && echo -e "\033[1;32m[ON]" || echo -e "\033[1;31m[OFF]"
+}
+menu_inst () {
+clear
+msg -bar
+echo -e "\033[1;37m       =====>>►► PANEL •ADMIN VPS• ◄◄<<=====       \033[1;37m"
+msg -bar
+export -f fun_eth
+export -f fun_bar
+menuTXT=" VOLVER"
+msg -ama "                  MENU DE PROTOCOLOS "
+msg -bar
+local Numb=1
+for arqs in $(ls ${SCPinst}); do
+float_data "$arqs" "$Numb" && {
+  script[$Numb]="$arqs"
+  let Numb++
+  }
+done
+msg -bar
+echo -ne "$(msg -verd "[0]") $(msg -verm2 "==>>") "&& msg -bra "\033[1;41mREGRESAR AL MENU"
+#echo -ne "$(msg -verd " [0]") $(msg -verm2 "==>>") " && msg -bra "$menuTXT"
+msg -bar
+script[0]="voltar"
+selection=999
+selection=$(selection_fun $Numb)
+[[ -e "${SCPinst}/${script[$selection]}" ]] && {
+  ${SCPinst}/${script[$selection]} 
+  } || return 0
+}
+# MENU FLUTUANTE
+menu_func () {
+local options=${#@}
+local array
+for((num=1; num<=$options; num++)); do
+echo -ne "  $(msg -verd "[$num]") $(msg -verm2 "=>>") "
+  array=(${!num})
+  case ${array[0]} in
+    "-vd")msg -verd "\033[1;33m[!]\033[1;32m $(fun_trans "${array[@]:1}")" | sed ':a;N;$!ba;s/\n/ /g';;
+    "-vm")msg -verm2 "\033[1;33m[!]\033[1;31m $(fun_trans "${array[@]:1}")" | sed ':a;N;$!ba;s/\n/ /g';;
+    "-fi")msg -azu "$(fun_trans "${array[@]:2}") ${array[1]}" | sed ':a;N;$!ba;s/\n/ /g';;
+    *)msg -azu "$(fun_trans "${array[@]}")" | sed ':a;N;$!ba;s/\n/ /g';;
+  esac
+done
+}
+# SISTEMA DE SELECAO
+selection_fun () {
+local selection="null"
+local range
+for((i=0; i<=$1; i++)); do range[$i]="$i "; done
+while [[ ! $(echo ${range[*]}|grep -w "$selection") ]]; do
+echo -ne "\033[1;37m$(fun_trans "Selecione una Opcion"): " >&2
+read selection
+tput cuu1 >&2 && tput dl1 >&2
+done
+echo $selection
+}
+# EXECUCION DE MENU
+export -f msg
+export -f selection_fun
+export -f fun_trans
+export -f  menu_func
+export -f meu_ip
+export -f fun_ip
+clear
+#########VISUALIZACION DE MENU
+msg -bar
+echo -e "\e[97m\033[1;41m       =====>>►► PANEL • ADMIN VPS • ◄◄<<=====       \033[1;37m"
+msg -bar
+msg -bra "   VERSION INSTALADA: \033[1;32m[\033[1;32m $vesaoSCTNEW\033[1;97m"
+msg -bra "   VERSION ANTERIOR:  \033[1;31m[\033[1;32m $vesaoSCT\033[1;97m"
+#[[ -e ${SCPdir}/key.txt ]] && msg -bar && msg -bra " KEY: \033[1;93m$(cat ${SCPdir}/key.txt)"
+[[ -e ${SCPdir}/message.txt ]] && msg -bar && msg -bra " RESELLER:\033[1;96m $(cat ${SCPdir}/message.txt) "
+msg -bra " CONTACTO: \033[1;31m[\033[1;32m +52 9842147259 \033[1;31m] "
+msg -bar
+echo -e "\033[1;31m     CPU: \033[1;37mNo.DE NUCLEOS :\033[1;32m $_core \033[1;31m USO DE CPU: \033[1;32m$_usop "
+echo -e "\033[1;31m     RAM: \033[1;37m TOTAL: \033[1;32m$ram1 \033[1;31m    USO DE RAM: \033[1;32m$_usor"
+msg -ne "     S.O: " && echo -ne "\033[1;37m$(os_system)"
+msg -ne "     IP: " && echo -e "\033[1;37m$(meu_ip)"
+msg -bar
+
+#MONITOR DE SERVICIOS
+monservi_fun () {
+clear
+monssh () {
+sed -i "57d" /bin/monitor.sh
+sed -i '57i EstadoServicio ssh' /bin/monitor.sh
+}
+mondropbear () {
+sed -i "59d" /bin/monitor.sh
+sed -i '59i EstadoServicio dropbear' /bin/monitor.sh
+}
+monssl() {
+sed -i "61d" /bin/monitor.sh
+sed -i '61i EstadoServicio stunnel4' /bin/monitor.sh
+}
+monsquid() {
+sed -i "63d" /bin/monitor.sh
+sed -i '63i [[ $(EstadoServicio squid) ]] && EstadoServicio squid3' /bin/monitor.sh
+}
+monapache() {
+sed -i "65d" /bin/monitor.sh
+sed -i '65i EstadoServicio apache2' /bin/monitor.sh
+}
+msg -bar
+echo -e "\033[1;37m       =====>>►► PANEL •ADMIN VPS• ◄◄<<=====       \033[1;37m"
+msg -bar
+echo -e "\033[1;32m          MONITOR DE SERVICIONS PRINCIPALES"
+
+PIDVRF3="$(ps aux|grep "${SCPdir}/menu monitorservi"|grep -v grep|awk '{print $2}')"
+
+PIDVRF5="$(ps aux|grep "${SCPdir}/menu moni2"|grep -v grep|awk '{print $2}')"
+
+if [[ -z $PIDVRF3 ]]; then
+sed -i '5a\screen -dmS very3 /etc/newadm/menu monitorservi' /bin/resetsshdrop
+msg -bar
+echo -e "\033[1;34m          ¿Monitorear Protocolo SSH/SSHD?"
+msg -bar
+read -p "                    [ s | n ]: " monssh  
+sed -i "57d" /bin/monitor.sh
+sed -i '57i #EstadoServicio ssh' /bin/monitor.sh 
+[[ "$monssh" = "s" || "$monssh" = "S" ]] && monssh
+msg -bar
+echo -e "\033[1;34m          ¿Monitorear Protocolo DROPBEAR?"
+msg -bar
+read -p "                    [ s | n ]: " mondropbear  
+sed -i "59d" /bin/monitor.sh
+sed -i '59i #EstadoServicio dropbear' /bin/monitor.sh
+[[ "$mondropbear" = "s" || "$mondropbear" = "S" ]] && mondropbear
+msg -bar
+echo -e "\033[1;34m            ¿Monitorear Protocolo SSL?"
+msg -bar
+read -p "                    [ s | n ]: " monssl  
+sed -i "61d" /bin/monitor.sh
+sed -i '61i #EstadoServicio stunnel4' /bin/monitor.sh
+[[ "$monssl" = "s" || "$monssl" = "S" ]] && monssl
+msg -bar
+echo -e "\033[1;34m            ¿Monitorear Protocolo SQUID?"
+msg -bar
+read -p "                    [ s | n ]: " monsquid  
+sed -i "63d" /bin/monitor.sh
+sed -i '63i #[[ $(EstadoServicio squid) ]] && EstadoServicio squid3' /bin/monitor.sh
+[[ "$monsquid" = "s" || "$monsquid" = "S" ]] && monsquid
+msg -bar
+echo -e "\033[1;34m            ¿Monitorear Protocolo APACHE?"
+msg -bar
+read -p "                    [ s | n ]: " monapache  
+sed -i "65d" /bin/monitor.sh
+sed -i '65i #EstadoServicio apache2' /bin/monitor.sh
+[[ "$monapache" = "s" || "$monapache" = "S" ]] && monapache
+
+
+
+#echo "screen -dmS very3 /etc/newadm/menu monitorservi" >> /bin/resetsshdrop
+cd ${SCPdir}
+screen -dmS very3 ${SCPdir}/menu monitorservi
+screen -dmS monis2 ${SCPdir}/menu moni2
+else
+
+
+for pid in $(echo $PIDVRF3); do
+kill -9 $pid &>/dev/null
+sed -i "6d" /bin/resetsshdrop
+done
+
+for pid in $(echo $PIDVRF5); do
+kill -9 $pid &>/dev/null
+done
+
+
+fi
+msg -bar
+echo -e "             Puedes Monitorear desde:\n       \033[1;32m http://$(meu_ip):81/monitor.html"
+msg -bar
+[[ -z ${VERY3} ]] && monitorservi="\033[1;32m ACTIVADO " || monitorservi="\033[1;31m DESACTIVADO "
+echo -e "            $monitorservi  --  CON EXITO"
+msg -bar
+
+}
+monhtop () {
+clear 
+msg -bar
+msg -tit
+echo -ne " \033[1;93m             MONITOR DE PROCESOS HTOP\n"
+msg -bar
+msg -bra "    RECUERDA SALIR CON : \033[1;96m CTRL + C o FIN + F10 "
+[[ $(dpkg --get-selections|grep -w "htop"|head -1) ]] || apt-get install htop -y &>/dev/null
+msg -bar
+read -t 10 -n 1 -rsp $'\033[1;39m Preciona Enter Para continuar\n'
+clear
+sudo htop
+msg -bar
+msg -tit
+echo -ne " \033[1;93m             MONITOR DE PROCESOS HTOP\n"
+msg -bar
+echo -e "\e[97m                  FIN DEL MONITOR"
+msg -bar
+}
+#TIMER MONITOR
+monitor_auto () {
