Update menu

diff --git a/gerador/menu b/gerador/menu
--- a/gerador/menu
+++ b/gerador/menu
@@ -298,3 +298,303 @@ done
 echo -ne "$(msg -verd " [0]") $(msg -verm2 "=>>") " && msg -bra "$(fun_trans "  VOLVER")"
 script[0]="voltar"
 msg -bar2
+selection=999
+selection=$(selection_fun $Numb)
+[[ -e "${SCPfrm}/${script[$selection]}" ]] && rm ${SCPfrm}/${script[$selection]} || return
+}
+agregar_ferramenta () {
+tput cuu1 && tput dl1
+msg -bar2
+unset Key
+echo -e "\033[1;31m$(fun_trans "ATENCION"): "
+echo -e "\033[1;33m$(fun_trans "No introduzca una clave de actualizacion aqui")"
+echo -e "\033[1;37m$(fun_trans "Introdusca una  clave para la nueva herramienta") "
+msg -bar2
+while [[ -z $Key ]]; do
+echo -ne "[Key/Link]: " && read Key
+tput cuu1 && tput dl1
+done
+echo -ne "\033[1;37m$(fun_trans "Verificando key"): "
+cd ${SCPfrm}
+curl "$Key" &> /dev/null
+if [[ $? = "0" ]]; then
+echo -e "\033[1;32m $(fun_trans "Link Valido")"
+REC=$(echo $Key|awk -F"/" '{print $NF}')
+echo -ne "\033[1;33m$(fun_trans "Recibendo Recurso"): \033[1;31m[$REC]"
+wget -O ${SCPfrm}/${REC} $Key &>/dev/null && echo -e "\033[1;31m- \033[1;32m$(fun_trans "Recebido")" && chmod +x ${SCPfrm}/${REC} || echo -e "\033[1;31m- \033[1;31m$(fun_trans "Erro al Recibir")"
+else
+wget $(ofus "$Key") >/dev/null 2>&1 && echo -e "\033[1;32m $(fun_trans "Key Valida")" || {
+    msg -verm "$(fun_trans "Key invalida")"
+    msg -bar2
+    return 0   
+    }
+fi
+IP=$(ofus "$Key" | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
+sleep 1s
+[[ -e ${SCPfrm}/lista-arq ]] && {
+  if [[ $(cat ${SCPfrm}/lista-arq) = "KEY DE INSTALACION!" ]]; then
+  echo -e "\033[1;33m$(fun_trans "KEY DE INSTALACION NO DEVE SER USADA AQUI")"
+  msg -bar2
+  rm ${SCPfrm}/lista-arq
+  return 1
+  fi
+  if [[ $(cat ${SCPfrm}/lista-arq) = "KEY INVALIDA!" ]]; then
+  echo -e "\033[1;33m$(fun_trans "KEY INVALIDA")"
+  msg -bar2
+  rm ${SCPfrm}/lista-arq
+  return 1
+  fi
+  REQUEST=$(ofus "$Key" |cut -d'/' -f2)
+  for arqx in $(cat ${SCPfrm}/lista-arq); do
+  echo -ne "\033[1;33m$(fun_trans "Recibiendo Recurso"): \033[1;31m[$arqx] "
+  wget -O ${SCPfrm}/${arqx} ${IP}:81/${REQUEST}/${arqx} > /dev/null 2>&1 && echo -e "\033[1;31m- \033[1;32m$(fun_trans "Recebido")" && chmod +x ${SCPfrm}/${arqx} || echo -e "\033[1;31m- \033[1;31m$(fun_trans "Erro al Recibir")"
+  sleep 1s
+  done
+  rm ${SCPfrm}/lista-arq
+  msg -bar2
+  } 
+}
+limpar_caches () {
+(
+VE="\033[1;33m" && MA="\033[1;31m" && DE="\033[1;32m"
+while [[ ! -e /tmp/abc ]]; do
+A+="#"
+echo -e "${VE}[${MA}${A}${VE}]" >&2
+sleep 0.3s
+tput cuu1 && tput dl1
+done
+echo -e "${VE}[${MA}${A}${VE}] - ${DE}[100%]" >&2
+rm /tmp/abc
+) &
+echo 3 > /proc/sys/vm/drop_caches &>/dev/null
+sleep 1s
+sysctl -w vm.drop_caches=3 &>/dev/null
+apt-get autoclean -y &>/dev/null
+sleep 1s
+apt-get clean -y &>/dev/null
+rm /tmp/* &>/dev/null
+touch /tmp/abc
+sleep 0.5s
+msg -bar
+msg -ama "$(fun_trans "PROCESO CONCLUIDO")"
+msg -bar
+}
+fun_autorun () {
+if [[ -e /etc/bash.bashrc-bakup ]]; then
+mv -f /etc/bash.bashrc-bakup /etc/bash.bashrc
+cat /etc/bash.bashrc | grep -v "/etc/newadm/menu" > /tmp/bash
+mv -f /tmp/bash /etc/bash.bashrc
+msg -ama "$(fun_trans "REMOVIDO CON EXITO")"
+msg -bar
+elif [[ -e /etc/bash.bashrc ]]; then
+cat /etc/bash.bashrc|grep -v /bin/adm > /etc/bash.bashrc.2
+echo '/etc/newadm/menu' >> /etc/bash.bashrc.2
+cp /etc/bash.bashrc /etc/bash.bashrc-bakup
+mv -f /etc/bash.bashrc.2 /etc/bash.bashrc
+msg -ama "$(fun_trans "AUTO INICIALIZAR AGREGADO")"
+msg -bar
+fi
+}
+fun_bar () {
+comando="$1"
+ _=$(
+$comando > /dev/null 2>&1
+) & > /dev/null
+pid=$!
+while [[ -d /proc/$pid ]]; do
+echo -ne " \033[1;33m["
+   for((i=0; i<10; i++)); do
+   echo -ne "\033[1;31m##"
+   sleep 0.2
+   done
+echo -ne "\033[1;33m]"
+sleep 1s
+echo
+tput cuu1
+tput dl1
+done
+echo -e " \033[1;33m[\033[1;31m####################\033[1;33m] - \033[1;32m100%\033[0m"
+sleep 1s
+}
+meu_ip () {
+if [[ -e /etc/MEUIPADM ]]; then
+echo "$(cat /etc/MEUIPADM)"
+else
+MEU_IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
+MEU_IP2=$(wget -qO- ifconfig.me)
+[[ "$MEU_IP2" != "$MEU_IP2" ]] && echo "$MEU_IP2" || echo "$MEU_IP"
+echo "$MEU_IP2" > /etc/MEUIPADM
+fi
+}
+fun_ip () {
+if [[ -e /etc/MEUIPADM ]]; then
+IP="$(cat /etc/MEUIPADM)"
+else
+MEU_IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
+MEU_IP2=$(wget -qO- ifconfig.me)
+[[ "$MEU_IP" != "$MEU_IP2" ]] && IP="$MEU_IP2" || IP="$MEU_IP"
+echo "$MEU_IP2" > /etc/MEUIPADM
+fi
+}
+fun_eth () {
+eth=$(ifconfig | grep -v inet6 | grep -v lo | grep -v 127.0.0.1 | grep "encap:Ethernet" | awk '{print $1}')
+    [[ $eth != "" ]] && {
+    msg -bar
+    msg -ama " $(fun_trans "Aplicar el sistema para mejorar los paquetes SSH?")"
+    msg -ama " $(fun_trans "Opciones para usuarios avanzados")"
+    msg -bar
+    read -p " [S/N]: " -e -i n sshsn
+           [[ "$sshsn" = @(s|S|y|Y) ]] && {
+           echo -e "${cor[1]} $(fun_trans "Correccion de problemas de paquetes en SSH ...")"
+           echo -e " $(fun_trans "¿Cual es la tasa RX?")"
+           echo -ne "[ 1 - 999999999 ]: "; read rx
+           [[ "$rx" = "" ]] && rx="999999999"
+           echo -e " $(fun_trans "¿Cual es la tasa TX?")"
+           echo -ne "[ 1 - 999999999 ]: "; read tx
+           [[ "$tx" = "" ]] && tx="999999999"
+           apt-get install ethtool -y > /dev/null 2>&1
+           ethtool -G $eth rx $rx tx $tx > /dev/null 2>&1
+           }
+     msg -bar
+     }
+}
+
+
+os_system () {
+system=$(echo $(cat -n /etc/issue |grep 1 |cut -d' ' -f6,7,8 |sed 's/1//' |sed 's/      //'))
+echo $system|awk '{print $1, $2}'
+}
+
+
+remove_script () {
+clear 
+msg -bar
+msg -ama "          ¿ DESEA DESINSTALAR SCRIPT ?"
+msg -bar
+echo -e " Esto borrara todos los archivos del script"
+msg -bar
+while [[ ${yesno} != @(s|S|y|Y|n|N) ]]; do
+read -p " [S/N]: " yesno
+tput cuu1 && tput dl1
+done
+if [[ ${yesno} = @(s|S|y|Y) ]]; then
+rm -rf ${SCPdir} &>/dev/null
+rm -rf ${SCPusr} &>/dev/null
+rm -rf ${SCPinst} &>/dev/null
+[[ -e /bin/adm ]] && rm /bin/adm
+[[ -e /usr/bin/adm ]] && rm /usr/bin/adm
+[[ -e /bin/menu ]] && rm /bin/menu
+[[ -e /usr/bin/menu ]] && rm /usr/bin/menu
+cd $HOME
+fi
+}
+
+# Menu Ferramentas
+systen_info () {
+msg -ama "$(fun_trans "DETALLES DEL SISTEMA")"
+null="\033[1;31m"
+msg -bar
+if [ ! /proc/cpuinfo ]; then msg -verm "$(fun_trans "Sistema No Soportado")" && msg -bar; return 1; fi
+if [ ! /etc/issue.net ]; then msg -verm "$(fun_trans "Sistema No Soportado")" && msg -bar; return 1; fi
+if [ ! /proc/meminfo ]; then msg -verm "$(fun_trans "Sistema No Soportado")" && msg -bar; return 1; fi
+totalram=$(free | grep Mem | awk '{print $2}')
+usedram=$(free | grep Mem | awk '{print $3}')
+freeram=$(free | grep Mem | awk '{print $4}')
+swapram=$(cat /proc/meminfo | grep SwapTotal | awk '{print $2}')
+system=$(cat /etc/issue.net)
+clock=$(lscpu | grep "CPU MHz" | awk '{print $3}')
+based=$(cat /etc/*release | grep ID_LIKE | awk -F "=" '{print $2}')
+processor=$(cat /proc/cpuinfo | grep "model name" | uniq | awk -F ":" '{print $2}')
+cpus=$(cat /proc/cpuinfo | grep processor | wc -l)
+[[ "$system" ]] && msg -ama "$(fun_trans "Sistema"): ${null}$system" || msg -ama "$(fun_trans "Sistema"): ${null}???"
+[[ "$based" ]] && msg -ama "$(fun_trans "Base"): ${null}$based" || msg -ama "$(fun_trans "Base"): ${null}???"
+[[ "$processor" ]] && msg -ama "$(fun_trans "Procesador"): ${null}$processor x$cpus" || msg -ama "$(fun_trans "Procesador"): ${null}???"
+[[ "$clock" ]] && msg -ama "$(fun_trans "Frecuencia de Operacion"): ${null}$clock MHz" || msg -ama "$(fun_trans "Frecuencia de Operacion"): ${null}???"
+msg -ama "$(fun_trans "Uso del Procesador"): ${null}$(ps aux  | awk 'BEGIN { sum = 0 }  { sum += sprintf("%f",$3) }; END { printf " " "%.2f" "%%", sum}')"
+msg -ama "$(fun_trans "Memoria Virtual Total"): ${null}$(($totalram / 1024))"
+msg -ama "$(fun_trans "Memoria Virtual En Uso"): ${null}$(($usedram / 1024))"
+msg -ama "$(fun_trans "Memoria Virtual Libre"): ${null}$(($freeram / 1024))"
+msg -ama "$(fun_trans "Memoria Virtual Swap"): ${null}$(($swapram / 1024))MB"
+msg -ama "$(fun_trans "Tempo Online"): ${null}$(uptime)"
+msg -ama "$(fun_trans "Nombre De La Maquina"): ${null}$(hostname)"
+msg -ama "$(fun_trans "IP De La  Maquina"): ${null}$(ip addr | grep inet | grep -v inet6 | grep -v "host lo" | awk '{print $2}' | awk -F "/" '{print $1}')"
+msg -ama "$(fun_trans "Version de Kernel"): ${null}$(uname -r)"
+msg -ama "$(fun_trans "Arquitectura"): ${null}$(uname -m)"
+msg -bar
+return 0
+}
+float_data () {
+valuest=$(ps ax |grep /etc/shadowsocks-r|grep -v grep)
+[[ $valuest != "" ]] && valuest="\033[1;32m[ON]" || valuest="\033[1;31m[OFF]"
+ofc="\033[0m${gren}(#OFICIAL)"
+dev="\033[0m${yellow}(#BETA)"
+dev2="\033[0m${red}(#PREMIUM)"
+case $1 in
+"ADMbot-VEN.sh")echo -ne "$(msg -verd " [$2]") $(msg -verm2 "=>>") " && msg -azu "BOT-USA1 VENTAS $dev2";;
+"openssh.sh")echo -ne "$(msg -verd " [$2]") $(msg -verm2 "==>>") " && msg -azu "OPENSSH $(pid_inst sshd)";;
+"squid.sh")echo -ne "$(msg -verd " [$2]") $(msg -verm2 "==>>") " && msg -azu "SQUID ---------------------------- $(pid_inst squid)";;
+"dropbear.sh")echo -ne "$(msg -verd " [$2]") $(msg -verm2 "==>>") " && msg -azu "DROPBEAR ------------------------- $(pid_inst dropbear)";;
+"openvpn.sh")echo -ne "$(msg -verd " [$2]") $(msg -verm2 "==>>") " && msg -azu "OPENVPN -------------------------- $(pid_inst openvpn)";;
+"ssl.sh")echo -ne "$(msg -verd " [$2]") $(msg -verm2 "==>>") " && msg -azu "SSL ------------------------------ $(pid_inst stunnel4)";;
+"shadowsocks.sh")echo -ne "$(msg -verd " [$2]") $(msg -verm2 "==>>") " && msg -azu "SHADOWSOCKS-NORMAL --------------- $(pid_inst ssserver)";;
+"Shadowsocks-libev.sh")echo -ne "$(msg -verd " [$2]") $(msg -verm2 "==>>") " && msg -azu "SHADOWSOCKS-LIBEV ---------------- $(pid_inst ss-server)";;
+"Shadowsocks-R.sh")echo -ne "$(msg -verd " [$2]") $(msg -verm2 "==>>") " && msg -azu "SHADOWSOCKS-R -------------------- ${valuest}";; 
+"sockspy.sh")echo -ne "$(msg -verd " [$2]") $(msg -verm2 "==>>") " && msg -azu "SOCKS PYTHON --------------------- $(pid_inst python)";;
+"v2ray.sh")echo -ne "$(msg -verd "[$2]") $(msg -verm2 "==>>") " && msg -azu "V2RAY ---------------------------- $(pid_inst v2ray)";; 
+"v2ui.sh")echo -ne "$(msg -verd "[$2]") $(msg -verm2 "==>>") " && msg -azu "V2-UI PANEL WEB ------------------ $(pid_inst v2-ui)";;
+"budp.sh")echo -ne "$(msg -verd " [$2]") $(msg -verm2 "==>>") " && msg -azu "BADVPN-(UDP:7300) ---------------- $(pid_inst badvpn)";;
+"trojanserver.sh")echo -ne "$(msg -verd "[$2]") $(msg -verm2 "==>>") " && msg -azu "TROJAN SERVER -------------------- $(pid_inst trojan)";;
+"payssl.sh")echo -ne "$(msg -verd " [$2]") $(msg -verm2 "==>>") " && msg -azu "WEBSOCKET ---------------- $(pid_inst python)";;
+
+"paysnd.sh")return 1;;
+"ultrahost")return 1;;
+"speed.sh")return 1;;
+"apacheon.sh")return 1;;
+"ports.sh")return 1;;
+"dns-netflix.sh")return 1;;
+"tcp.sh")return 1;;
+"gestor.sh")return 1;;
+"Unlock-Pass-VULTR.sh")return 1;;
+"squidpass.sh")return 1;;
+"fai2ban.sh")return 1;;
+"blockBT.sh")return 1;;
+"utils.sh")return 1;;
+"ADMbot.sh")return 1;;
+"C-SSR.sh")return 1;;
+"Crear-Demo.sh")return 1;;
+"pwd.pwd")return 1;;
+"PDirect.py")return 1;;
+"PGet.py")return 1;;
+"POpen.py")return 1;;
+"PPriv.py")return 1;;
+"PPub.py")return 1;;
+"speedtest.py")return 1;;
+"SSH20.log")return 1;; 
+"panelweb.sh")return 1;; 
+"optimizar.sh")return 1;;
+"vnc")return 1;;
+*)echo -ne "$(msg -verd " [$2]") $(msg -verm2 "==>>") " && msg -azu "${1^^} \033[1;33m($(fun_trans "No Hay Una Descripcion")!)";;
+esac
+}
+
+#aviso_bock () {
+  #echo 'echo -e "\033[1;91m==============================================================\n¡SCRIPT BLOQUEADO CONTACTE A @Kalix1 PARA VER MOTIVOS!\n=============================================================="' > /usr/bin/menu
+  #echo 'echo -e "\033[1;91m==============================================================\n¡SCRIPT BLOQUEADO CONTACTE A @Kalix1 PARA VER MOTIVOS!\n=============================================================="' > /usr/bin/adm
+ #rm -rf /etc/newadm
+#}
+
+#[[ ! -e $(echo -e $(echo "2f7573722f6c6f63616c2f6c69622f6c73797374656d62696e32"| sed 's/../\\x&/g;s/$/ /')) ]] && $( aviso_bock > /dev/null 2>&1)
+
+ferramentas_fun () {
+clear
+
+tput cuu1 && tput dl1
+msg -bar2
+echo -e "\033[1;37m       =====>>►►PANEL •ADMIN VPS• ◄◄<<=====       \033[1;37m"
+msg -bar
+msg -ama "                 MENU DE HERRAMIENTAS"
+msg -bar2
+local Numb=1
+for arqs in $(ls ${SCPfrm}); do
+float_data "$arqs" "$Numb" && {
+  script[$Numb]="$arqs"
